const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),E=require('../web/engine'),{files}=require('./browser_helpers');
test('alphabet overview shows gaps, saves a preferred sample and clears it',async()=>{
 function element(tag='div'){return {tag,children:[],value:'',attrs:{},listeners:{},setAttribute(k,v){this.attrs[k]=v;},append(...nodes){this.children.push(...nodes);if(tag==='select'&&!this.value)this.value=nodes[0]?.value||'';},replaceChildren(){this.children=[];this.value='';},addEventListener(k,v){this.listeners[k]=v;}};}
 const ids=Object.fromEntries(['alphabet-writer','alphabet-kind','alphabet-refresh','alphabet-summary','alphabet-gaps','alphabet-status','alphabet-grid','alphabet-samples','alphabet-compose','alphabet-heading','alphabet-choice','alphabet-clear'].map(id=>[id,element(id==='alphabet-writer'||id==='alphabet-kind'?'select':'div')]));ids['alphabet-kind'].value='lowercase';
 let records=files(),requests=[],revoked=0,images=0;const doc={hidden:false,getElementById:id=>ids[id],createElement:element,querySelectorAll:()=>[],addEventListener(){}};
 const context={document:doc,StudioEngine:E,StudioStorage:{snapshot:async()=>records},Blob,URLSearchParams,URL:{createObjectURL:()=>String(++images),revokeObjectURL:()=>revoked++},location:{search:'?writer=Writer'},addEventListener(){},studioFetch:async(url,options)=>{const data=JSON.parse(options.body);requests.push(data);const r=E.choosePreferred(records,data);records=records.filter(f=>f.key!==r.key).concat(r);return {ok:true,json:async()=>({saved:true})};}};context.window=context;
 await vm.runInNewContext(fs.readFileSync('web/alphabet.js','utf8'),context);
 assert.equal(ids['alphabet-grid'].children.length,26);assert(ids['alphabet-summary'].textContent.includes('26 of 26'));assert(ids['alphabet-gaps'].textContent.includes('No included saved blend yet'));assert.equal(ids['alphabet-samples'].children.length,3);
 const sampleButton=ids['alphabet-samples'].children[2].children[2];await sampleButton.onclick();assert.equal(requests[0].letter,'a');assert(ids['alphabet-choice'].textContent.startsWith('Preferred:'));assert.equal(ids['alphabet-clear'].disabled,false);assert(ids['alphabet-status'].textContent.includes('saved'));
 await ids['alphabet-clear'].onclick();assert.equal(requests[1].capture_id,null);assert.equal(ids['alphabet-clear'].disabled,true);assert(ids['alphabet-compose'].href.includes('writer=Writer'));
 ids['alphabet-kind'].value='uppercase';ids['alphabet-kind'].listeners.change();assert(ids['alphabet-summary'].textContent.includes('0 of 26'));assert.equal(ids['alphabet-samples'].children.length,0);assert(ids['alphabet-choice'].textContent.includes('No samples'));assert(revoked>0);
});
