const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),E=require('../web/engine.js'),{files}=require('./browser_helpers'),{webcrypto}=require('node:crypto');
test('single-character workspace previews slider changes and saves the selected sources',async()=>{
 function element(tag='div'){return {tag,attrs:{},setAttribute(name,value){this.attrs[name]=value;},set innerHTML(value){this.children=[...value.matchAll(/<path d="([^"]+)"/g)].map(m=>{const p=element('path');p.setAttribute('d',m[1]);return p;});},value:'',children:[],listeners:{},dataset:{},append(...nodes){this.children.push(...nodes);if(this.tag==='select'&&!this.value&&nodes[0]?.value)this.value=nodes[0].value;},replaceChildren(){this.children=[];this.value='';},get options(){return this.children;},querySelectorAll(tag){return this.children.flatMap(c=>typeof c==='string'?[]:[...(c.tag===tag?[c]:[]),...c.querySelectorAll(tag)]);},addEventListener(name,fn){this.listeners[name]=fn;}};}
 const ids={};for(const id of ['single-pool','single-writer','single-letter','single-count','single-vertical-label','single-horizontal','single-horizontal-value','single-vertical','single-vertical-value','single-sources','single-cards','single-save','single-refresh','blend-status'])ids[id]=element(['single-pool','single-writer','single-letter','single-count'].includes(id)?'select':'div');
 ids['single-pool'].value='writer';ids['single-count'].value='2';ids['single-horizontal'].value='50';ids['single-vertical'].value='50';let records=files(),created=[],requests=[];
 const doc={getElementById:id=>ids[id],createElement:element,createElementNS:(_,tag)=>element(tag),querySelectorAll:()=>[]},context={document:doc,crypto:webcrypto,Blob,URL:{createObjectURL:blob=>{created.push(blob);return 'blob:'+created.length;},revokeObjectURL(){}},StudioEngine:E,StudioStorage:{snapshot:async()=>records},studioFetch:async(url,options)=>{requests.push(JSON.parse(options.body));return {ok:true,json:async()=>({id:requests.at(-1).id})};}};context.window=context;
 await vm.runInNewContext(fs.readFileSync('web/blending.js','utf8'),context);
 assert.equal(ids['single-save'].disabled,false);assert.equal(ids['single-cards'].children.length,3);
 const selectors=ids['single-sources'].querySelectorAll('select'),first=selectors[0].value,second=selectors[1].value;assert.notEqual(first,second);
 selectors[0].value=second;selectors[0].listeners.change();assert.equal(selectors[1].value,first);assert.equal(selectors[0].value,second);
 selectors[1].value=second;selectors[1].listeners.change();assert.equal(selectors[0].value,first);assert.equal(selectors[1].value,second);
 selectors[1].value=selectors[1].options.find(o=>o.value&&o.value!==first&&o.value!==second).value;selectors[1].listeners.change();assert.notEqual(selectors[0].value,selectors[1].value);
 const cards=ids['single-cards'].children.slice(),sourceSVG=cards[0].children[1],resultSVG=cards[2].children[1],resultPaths=resultSVG.querySelectorAll('path'),viewBox=resultSVG.attrs.viewBox;
 const old=resultPaths[0].attrs.d,sourcePath=sourceSVG.querySelectorAll('path')[0].attrs.d;
 for(const value of ['0','30','70','100']){ids['single-horizontal'].value=value;ids['single-horizontal'].listeners.input();assert.equal(ids['single-cards'].children[2],cards[2]);assert.equal(cards[2].children[1],resultSVG);assert.equal(resultSVG.querySelectorAll('path')[0],resultPaths[0]);assert.equal(resultSVG.attrs.viewBox,viewBox);}
 assert.notEqual(old,resultPaths[0].attrs.d);assert.equal(sourceSVG.querySelectorAll('path')[0].attrs.d,sourcePath);assert.equal(created.length,0);
 await ids['single-save'].onclick();assert.equal(requests.length,1);assert.equal(requests[0].horizontal,100);assert.equal(requests[0].source_ids.length,2);assert(ids['blend-status'].textContent.includes('Saved a'));
 ids['single-count'].value='4';ids['single-count'].listeners.change();assert.equal(ids['single-save'].disabled,true);assert(ids['blend-status'].textContent.includes('distinct originals'));
 records=[records[0]];await ids['single-refresh'].onclick();
 const single=ids['single-sources'].querySelectorAll('select');assert.equal(single[1].value,'');assert.equal(single[1].disabled,true);assert(ids['blend-status'].textContent.includes('1 included original'));assert.equal(ids['single-save'].disabled,true);
 const original=records[0];records=Array.from({length:4},(_,i)=>{const r=E.clone(original);r.value.id=webcrypto.randomUUID();r.key='letters/'+r.value.id+'.json';r.value.writer='Gordon-00'+(i+1)+'-lower';return r;});await ids['single-refresh'].onclick();
 assert.equal(ids['single-save'].disabled,true);ids['single-pool'].value='all';ids['single-pool'].listeners.change();assert.equal(ids['single-save'].disabled,false);assert.equal(ids['single-sources'].querySelectorAll('select').length,4);
 const fourCards=ids['single-cards'].children.slice(),fourBox=fourCards[4].children[1].attrs.viewBox;ids['single-vertical'].value='90';ids['single-vertical'].listeners.input();assert.equal(ids['single-cards'].children[4],fourCards[4]);assert.equal(fourCards[4].children[1].attrs.viewBox,fourBox);
 await ids['single-save'].onclick();assert.equal(requests.at(-1).source_ids.length,4);
});
